- description: Serveurs personnels
  hostnames:
    - imirhil.fr
    - libwalk.so
    - www.keltia.net
    - quentin.demouliere.eu
    - rss.decornulier.eu
    - fralef.me
    - jeekajoo.eu
    - status.jbfavre.org
    - rosset.net
    - owc.h.arysthaar.pw
    - crifo.org
    - matlink.fr
- description: Banques en ligne
  hostnames:
    - www.labanquepostale.fr
    - www.secure.bnpparibas.net
    - www.axabanque.fr
    - www.fortuneo.fr
    - www.ca-paris.fr
    - www.credit-cooperatif.coop
    - www.cic.fr
    - particuliers.societegenerale.fr
    - espaceclient.groupama.fr
    - www.ibps.rivesparis.banquepopulaire.fr
    - ca-des-savoie.fr
    - particuliers.secure.lcl.fr
    - www.boursorama.com
    - bpe.fr
    - www.creditmutuel.fr
    - www.caisse-epargne.fr
    - paiement.systempay.fr
    - cnce.wlp-acs.com
    - www.cmb.fr
    - www.ca-paris.fr
    - www.ca-cotesdarmor.fr
    - secure.ingdirect.fr
    - banque-accord.fr
    - espace-client-secure.banque-casino.fr
    - bforbank.com
    - hellobank.fr
- description: Webmails
  hostnames:
    - webmail.mailden.fr
    - zimbra.free.fr
    - webmail.numericable.fr
    - webmail.orange-business.com
    - webmail.gandi.net
    - messagerie.sfr.fr
    - webmail.aliceadsl.fr
    - webmail.online.net
    - wmail.amen.fr
    - webmail.ovh.com
    - webmail.aliceadsl.fr
    - compte.laposte.net
- description: Administration
  hostnames:
    - assure.ameli.fr
    - ameli.moncompte.mobi
    - www.service-public.fr
    - cfspart.impots.gouv.fr
    - www.pole-emploi.fr
    - wwwd.caf.fr
    - www.cjn.justice.gouv.fr
    - www.interieur.gouv.fr
    - mon.service-public.fr
    - www.correspondants.cnil.fr
    - sso.quechoisir.org
- description: Sites de commerce en ligne
  hostnames:
    - signin.ebay.fr
    - secure.ldlc.com
    - grosbill.com
    - secure.darty.com
    - secure.boulanger.fr
    - www.capitainetrain.com
    - espace-client.voyages-sncf.com
    - www.pixmania.fr
    - clients.cdiscount.com
    - secure.ikea.com
    - secure.fnac.com
    - www.laredoute.fr
    - online.carrefour.fr
- description: Divers
  hostnames:
    - www.mailden.net
    - sharypic.com
    - google.fr
    - duckduckgo.com
    - octopuce.fr
